# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-screen/all/tty-screen.rbi
#
# tty-screen-0.8.1

module TTY
end
module TTY::Screen
  def cols; end
  def columns; end
  def command_exist?(command); end
  def height; end
  def ioctl?(control, buf); end
  def jruby?; end
  def lines; end
  def nonzero_column?(column); end
  def rows; end
  def run_command(*args); end
  def self.cols; end
  def self.columns; end
  def self.command_exist?(command); end
  def self.env; end
  def self.env=(arg0); end
  def self.height; end
  def self.ioctl?(control, buf); end
  def self.jruby?; end
  def self.lines; end
  def self.nonzero_column?(column); end
  def self.output; end
  def self.output=(arg0); end
  def self.private_module_function(name); end
  def self.rows; end
  def self.run_command(*args); end
  def self.size(verbose: nil); end
  def self.size_from_ansicon; end
  def self.size_from_default; end
  def self.size_from_env; end
  def self.size_from_io_console(verbose: nil); end
  def self.size_from_ioctl; end
  def self.size_from_java(verbose: nil); end
  def self.size_from_readline(verbose: nil); end
  def self.size_from_stty; end
  def self.size_from_tput; end
  def self.size_from_win_api(verbose: nil); end
  def self.width; end
  def self.windows?; end
  def size(verbose: nil); end
  def size_from_ansicon; end
  def size_from_default; end
  def size_from_env; end
  def size_from_io_console(verbose: nil); end
  def size_from_ioctl; end
  def size_from_java(verbose: nil); end
  def size_from_readline(verbose: nil); end
  def size_from_stty; end
  def size_from_tput; end
  def size_from_win_api(verbose: nil); end
  def width; end
  def windows?; end
end
