# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-cursor/all/tty-cursor.rbi
#
# tty-cursor-0.7.1

module TTY
end
module TTY::Cursor
  def backward(n = nil); end
  def clear_char(n = nil); end
  def clear_line; end
  def clear_line_after; end
  def clear_line_before; end
  def clear_lines(n, direction = nil); end
  def clear_rows(n, direction = nil); end
  def clear_screen; end
  def clear_screen_down; end
  def clear_screen_up; end
  def column(n = nil); end
  def current; end
  def cursor_backward(n = nil); end
  def cursor_down(n = nil); end
  def cursor_forward(n = nil); end
  def cursor_up(n = nil); end
  def down(n = nil); end
  def forward(n = nil); end
  def hide; end
  def invisible(stream = nil); end
  def move(x, y); end
  def move_to(row = nil, column = nil); end
  def next_line; end
  def prev_line; end
  def restore; end
  def row(n = nil); end
  def save; end
  def scroll_down; end
  def scroll_up; end
  def self.backward(n = nil); end
  def self.clear_char(n = nil); end
  def self.clear_line; end
  def self.clear_line_after; end
  def self.clear_line_before; end
  def self.clear_lines(n, direction = nil); end
  def self.clear_screen; end
  def self.clear_screen_down; end
  def self.clear_screen_up; end
  def self.column(n = nil); end
  def self.current; end
  def self.down(n = nil); end
  def self.forward(n = nil); end
  def self.hide; end
  def self.invisible(stream = nil); end
  def self.move(x, y); end
  def self.move_to(row = nil, column = nil); end
  def self.next_line; end
  def self.prev_line; end
  def self.restore; end
  def self.row(n = nil); end
  def self.save; end
  def self.scroll_down; end
  def self.scroll_up; end
  def self.show; end
  def self.up(n = nil); end
  def show; end
  def up(n = nil); end
end
